interface Formatname {
  id: number;
  name: string;
}

export const favoriteList: Formatname[] = [
  { id: 1, name: "Arroz" },
  { id: 2, name: "Feijão" },
  { id: 3, name: "Leite" },
  { id: 4, name: "Pão" },
  { id: 5, name: "Café" },
  { id: 6, name: "Açúcar" },
  { id: 7, name: "Óleo" },
  { id: 8, name: "Macarrão" },
  { id: 9, name: "Carne" },
  { id: 10, name: "Frango" },
  { id: 11, name: "Ovo" },
  { id: 12, name: "Tomate" },
  { id: 13, name: "Batata" },
  { id: 14, name: "Cebola" },
  { id: 15, name: "Alho" },
  { id: 16, name: "Banana" },
  { id: 17, name: "Sabão em pó" },
  { id: 18, name: "Detergente" },
  { id: 19, name: "Papel higiênico" },
  { id: 20, name: "Manteiga" },
  { id: 21, name: "Queijo" },
  { id: 22, name: "Requeijão" },
  { id: 23, name: "Creme de leite" },
  { id: 24, name: "Amaciante" },
  { id: 25, name: "Sabonete" },
  { id: 26, name: "Papel toalha" },
  { id: 27, name: "Pasta de dente" },
  { id: 28, name: "Desodorante" },
  { id: 29, name: "Maionese" },
  { id: 30, name: "Cenoura" },
  { id: 31, name: "Ketchup" },
  { id: 32, name: "Molho de tomate" },
  { id: 33, name: "Batata palha" },
  { id: 34, name: "Leite condensado" },
  { id: 35, name: "Cerveja" },
  { id: 36, name: "Suco" },
  { id: 37, name: "Guardanapo" },
  { id: 38, name: "Saco de lixo" },
  { id: 39, name: "Margarina" },
  { id: 40, name: "Chocolate" },
  { id: 41, name: "Alface" },
  { id: 42, name: "Queijo ralado" },
  { id: 43, name: "Presunto" },
  { id: 44, name: "Álcool" },
  { id: 45, name: "Desinfetante" },
  { id: 46, name: "Água sanitária" },
  { id: 47, name: "Nescau" },
  { id: 48, name: "Água" },
  { id: 49, name: "Bacon" },
  { id: 50, name: "Pão de queijo" },
  { id: 51, name: "Vinagre" },
  { id: 52, name: "Maçã" },
  { id: 53, name: "Milho" },
  { id: 54, name: "Frutas" },
  { id: 55, name: "Tapioca" },
  { id: 56, name: "Pão de forma" },
  { id: 57, name: "Cotonete" },
  { id: 58, name: "Xampu" },
  { id: 59, name: "Pipoca" },
  { id: 60, name: "Carne moída" },
  { id: 61, name: "Refrigerante" },
  { id: 62, name: "Farinha de trigo" },
  { id: 63, name: "Mamão" },
  { id: 64, name: "Sabonete líquido" },
  { id: 65, name: "Papel alumínio" },
  { id: 66, name: "Laranja" },
  { id: 67, name: "Aveia" },
  { id: 68, name: "Esponja" },
  { id: 69, name: "Farinha" },
  { id: 70, name: "Água com gás" },
  { id: 71, name: "Bombril" },
  { id: 72, name: "Leite em pó" },
  { id: 73, name: "Filtro de café" },
  { id: 74, name: "Sabão líquido" },
  { id: 75, name: "Miojo" },
  { id: 76, name: "Coca cola" },
  { id: 77, name: "Brócolis" },
  { id: 78, name: "Biscoito" },
  { id: 79, name: "Azeitona" },
  { id: 80, name: "Mostarda" },
  { id: 81, name: "Morango" },
  { id: 82, name: "Bolacha" },
  { id: 83, name: "Chá" },
  { id: 84, name: "Vinho" },
  { id: 85, name: "Granola" },
  { id: 86, name: "Adoçante" },
  { id: 87, name: "Atum" },
  { id: 88, name: "Frios" },
  { id: 89, name: "Peito de frango" },
  { id: 90, name: "Lenço umedecido" },
  { id: 91, name: "Farofa" },
  { id: 92, name: "Salsicha" },
  { id: 93, name: "Calabresa" },
  { id: 94, name: "Batata doce" },
];
