const favoriteList =  [
  "Leite",
  "Arroz",
  "Papel higiênico",
  "Manteiga",
  "Café",
  "Detergente",
  "Ovo",
  "Banana",
  "Pão",
  "Ovos",
  "Cebola",
  "Açúcar",
  "Azeite",
  "Tomate",
  "Papel toalha",
  "Sabonete",
  "Queijo",
  "Requeijão",
  "Alho",
  "Feijão",
  "Óleo",
  "Creme de leite",
  "Amaciante",
  "Sabão em pó",
  "Batata",
  "Limão",
  "Macarrão",
  "logurte",
  "Sal",
  "Desodorante",
  "Pasta de dente",
  "Maionese",
  "Cenoura",
  "Ketchup",
  "Molho de tomate",
  "Batata palha",
  "Leite condensado",
  "Carne",
  "Cerveja",
  "Suco",
  "Frango",
  "Guardanapo",
  "Saco de lixo",
  "Margarina",
  "Chocolate",
  "Alface",
  "Bananas",
  "Queijo ralado",
  "Presunto",
  "Álcool",
  "Desinfetante",
  "Água sanitária",
  "Nescau",
  "Água",
  "Bacon",
  "Pão de queijo",
  "Vinagre",
  "Maçã",
  "Milho",
  "Frutas adicionado",
  "Tapioca",
  "Pão de forma",
  "Cotonete",
  "Xampu",
  "Pipoca",
  "Carne moída",
  "Refrigerante",
  "Farinha de trigo",
  "Mamão",
  "Sabonete líquido",
  "Papel alumínio",
  "Laranja",
  "Aveia",
  "Esponja",
  "Farinha",
  "Água com gás",
  "Bombril",
  "Leite em pó",
  "Filtro de café",
  "Sabão líquido",
  "Miojo",
  "Coca cola",
  "Brócolis",
  "Biscoito",
  "Azeitona",
  "Mostarda",
  "Morango",
  "Bolacha",
  "Chá",
  "Vinho",
  "Granola",
  "Adoçante",
  "Atum",
  "Frios",
  "Peito de frango",
  "Lenço umedecido",
  "Farofa",
  "Salsicha",
  "Calabresa",
  "Batata doce",
];